default interface asset {
    use pkg.types.{entity-id, vec3}

    add-sound: func(index: u32, path: string)
    play-sound-on-entity: func(entity: entity-id, path: string)
    listener: func()
    emitter: func()
}